name: cronjob
on:
  schedule:
    - cron: "*/5 * * * *"
 
jobs:
  echo_repo_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Echo repository variable
        run: |
          echo "${{ vars.TEST }}"
